# Generated by Django 5.1.6 on 2025-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
    ]
