# Generated by Django 5.1.6 on 2025-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
