# Generated by Django 5.1.6 on 2025-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_admin_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
