# Generated by Django 5.1.6 on 2025-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='Not Applicable', max_length=20),
        ),
    ]
