# Generated by Django 5.1.6 on 2025-02-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
