# Generated by Django 5.1.6 on 2025-03-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_products_order_product_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
