# Generated by Django 5.1.6 on 2025-02-23 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customer_join_dated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaiton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=300)),
                ('notification_type', models.CharField(choices=[('Order Update', 'Order Update'), ('Delivery Update', 'Delivery Update')], default='Order Update', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
