# Generated by Django 5.1.6 on 2025-02-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='Not Applicable', max_length=25, null=True),
        ),
    ]
